### ISSUE TITLE
Cannot run ipns-link init

### ISSUE THREAD

**Issue by tcardel** [ipns-link/ipns-link#1]
I was following the [quick start](https://github.com/ipns-link/ipns-link/blob/main/tutorials/QuickStart.md) guide after reading your article on [medium](https://ipns-link.medium.com/introducing-ipns-link-36a14c87a4aa). Couldn't find any info on which systems can run this. 
Does this work on OSX? 

I get this when I run `ipns-link init` after running `sudo install ipns-link /usr/local/bin/` succesfully:

```MacBook-Pro:ipns-link thorecardel$ ipns-link init
/usr/local/bin/ipns-link: line 553: conditional binary operator expected
/usr/local/bin/ipns-link: line 553: syntax error near `quit'
/usr/local/bin/ipns-link: line 553: `  [[ -v quit ]] && echo "NOTE: The dependencies may also be installed locally at ${HOME}/.bin" && exit 1'
```

Thanks in advance 🙏

**Comment by SomajitDey** [comment]
@tcardel Hello.

`ipns-link` is just a simple Bash script. We tested it on Linux. Our requirements have been Bash, go-ipfs, jq, socat and some other standard Linux utilities, usually built-in standard Linux distros. I wanted to mention this in the Quick Start but totally forgot. Thanks a lot for letting me know.

You should not have problems running shell scripts in OSX, granted it might require some modifications. Let us know how it goes.

**Comment by tcardel** [comment]
@SomajitDey Hi!

Yes you're right, I didn't have `Bash` on my system. I'll try again! Looking forward to try it out.
