### ISSUE TITLE
Dig Dependency not installing correctly.

### ISSUE THREAD

**Issue by Kirbyrawr** [ipns-link/ipns-link#8]
Hi, i'm having issues trying to init ipns-link, it asks for dig dependency but i already have it installed.
The rest of dependencies didn't give me any issue, i guess is because of the path.

I know that dig is not a thing of this repository but i found that blocker when trying to follow the installation.

**Comment by Kirbyrawr** [comment]
I fixed it by doing this:

```
sudo apt-get update
sudo apt-get install dnsutils
```

**Comment by rinzler100** [comment]
Thank you for your feedback, so glad yo figured it out!
